// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyS-A26seM1Fn_gv5bMe6kfFKoVbxCEjc',
    appId: '1:287037071943:web:d2c45a56abcaed85114762',
    messagingSenderId: '287037071943',
    projectId: 'loginsignup-7cfd0',
    authDomain: 'loginsignup-7cfd0.firebaseapp.com',
    storageBucket: 'loginsignup-7cfd0.firebasestorage.app',
    measurementId: 'G-9748ZFM0F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZj7SeFCf4azJguUlg138OhXLyjJuskpg',
    appId: '1:287037071943:android:7c086507e47ce5f1114762',
    messagingSenderId: '287037071943',
    projectId: 'loginsignup-7cfd0',
    storageBucket: 'loginsignup-7cfd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK12kp9yOAuc0i_4slSwuNw5hEB2vawKM',
    appId: '1:287037071943:ios:93931708b6b1baca114762',
    messagingSenderId: '287037071943',
    projectId: 'loginsignup-7cfd0',
    storageBucket: 'loginsignup-7cfd0.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK12kp9yOAuc0i_4slSwuNw5hEB2vawKM',
    appId: '1:287037071943:ios:93931708b6b1baca114762',
    messagingSenderId: '287037071943',
    projectId: 'loginsignup-7cfd0',
    storageBucket: 'loginsignup-7cfd0.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyS-A26seM1Fn_gv5bMe6kfFKoVbxCEjc',
    appId: '1:287037071943:web:786c57a4ccbcfce4114762',
    messagingSenderId: '287037071943',
    projectId: 'loginsignup-7cfd0',
    authDomain: 'loginsignup-7cfd0.firebaseapp.com',
    storageBucket: 'loginsignup-7cfd0.firebasestorage.app',
    measurementId: 'G-YPJ8QYFZGL',
  );

}